### ISSUE TITLE
I find a conflict between this code and the relative paper!

### ISSUE THREAD

**Issue by yhao-z** [Keziwen/SLR-Net#2]
* In this code, the CNNs in SLR-Net in `model.py` is defined as 
```
        self.conv_1 = CONV_OP(n_f=16, ifactivate=True)
        self.conv_2 = CONV_OP(n_f=16, ifactivate=True)
        self.conv_3 = CONV_OP(n_f=16, ifactivate=False)
        self.conv_4 = CONV_OP(n_f=16, ifactivate=True)
        self.conv_5 = CONV_OP(n_f=16, ifactivate=True)
        self.conv_6 = CONV_OP(n_f=2, ifactivate=False)
```
* The channel of the 3d CNN is __16__ that is different with __32__ in your paper, and the `conv_3` op should have a `relu` activation.
![image](https://user-images.githubusercontent.com/59129069/162453232-c521e374-1e37-4b39-a9ac-f6c9c7d84074.png)
* However, if I change the code into
```
        self.conv_1 = CONV_OP(n_f=32, ifactivate=True)
        self.conv_2 = CONV_OP(n_f=32, ifactivate=True)
        self.conv_3 = CONV_OP(n_f=32, ifactivate=True)
        self.conv_4 = CONV_OP(n_f=32, ifactivate=True)
        self.conv_5 = CONV_OP(n_f=32, ifactivate=True)
        self.conv_6 = CONV_OP(n_f=2, ifactivate=False)
```
to be consistent with the original paper, the total parameters of this SLR-Net is equal to __1140528__ which is different with __441889__ in the paper.
![image](https://user-images.githubusercontent.com/59129069/162454106-dc0021a0-f21e-4039-869e-ad021546487a.png)
* __Please confirm this conflict. It really matters.__
     * I'm going to contrast your methods with mine, so it really matters to confirm that the results I reproduced are correct.

**Comment by Keziwen** [comment]
Hi Yinghao,

Thanks for your attention to our work! The parameter, 'niter', may should be set to 5. Then you can see if the total parameters is equal to 441889. ISTA-Net can be used as a baseline, as it differs from SLR-Net mainly in the LR Module. (5 * 4 = 441889 - 441869).

You can also communicate with me through the wechat for more detailed discussions. My wechat ID is: kzw_love_nw.

Best,
Ziwen

**Comment by yhao-z** [comment]
Thanks very much！

**Comment by Angqi-Li** [comment]
Dear author,

We trying to reimplentment your method in our work with our data. I got some problem with the 

```
 if acc == 8:
        mask = mat73.loadmat('/data1/ziwenke/SLRNet/mask_newdata/vista_' + mask_size + '_acc_8.mat')['mask']
  elif acc == 10:
      mask = mat73.loadmat('/data1/ziwenke/SLRNet/mask_newdata/vista_' + mask_size + '_acc_10.mat')['mask']
  elif acc == 12:
      mask = mat73.loadmat('/data1/ziwenke/SLRNet/mask_newdata/vista_' + mask_size + '_acc_12.mat')['mask']
```

what is the shape of the mask here? 

Best,
Angqi
